{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "impulse.fullname" . }}
  labels:
    {{- include "impulse.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "impulse.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  {{- if .Values.networkPolicy.ingressRules }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingressRules | nindent 4 }}
  {{- else }}
  ingress:
    - {}
  {{- end }}
  {{- if .Values.networkPolicy.egressRules }}
  egress:
    {{- toYaml .Values.networkPolicy.egressRules | nindent 4 }}
  {{- else }}
  egress:
    - {}
  {{- end }}
{{- end }}
