apiVersion: v2
name: impulse
description: Community Helm chart for IMPulse
type: application
version: "v1.0.7"
appVersion: "v3.3.0"
icon: https://raw.githubusercontent.com/eslupmi/impulse/refs/heads/develop/logo.svg
kubeVersion: ">=1.12.0-0"
keywords:
  - incident-management
  - alerting
  - slack
  - mattermost
  - telegram
home: https://artifacthub.io/packages/helm/impulse/impulse
sources:
  - https://github.com/eslupmi/impulse
maintainers:
  - name: Artem Vershinin
    email: artyom.vershinin@icloud.com
annotations:
  artifacthub.io/images: |
    - name: impulse
      image: ghcr.io/eslupmi/impulse:v3.3.0
  artifacthub.io/links: |
    - name: Site
      url: https://impulse.bot
    - name: Documentation
      url: https://docs.impulse.bot
    - name: Source Code
      url: https://github.com/eslupmi/impulse
  artifacthub.io/repositoryID: "8463be1d-2ded-4e14-b15c-2be5820ff537"
